/**
 * Lorem texts
 */
export class Lorems {

    public static mediumLength() {

        return `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec faucibus ligula. Ut nec consectetur nisi, in euismod ipsum. Curabitur euismod ipsum in enim varius consequat. Ut ligula justo, tristique in lacus non, imperdiet euismod tortor. Integer efficitur euismod erat a malesuada. Aliquam erat volutpat. Morbi ut tempus est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque efficitur est magna, quis pharetra ex hendrerit quis.

Proin tincidunt, quam eu ornare vehicula, nisl ipsum iaculis massa, ut sollicitudin leo nisl at sem. Mauris molestie nunc nec nisl sollicitudin, a venenatis ex dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies, odio at viverra dapibus, ligula ex vulputate libero, sed maximus velit sem et nibh. In hac habitasse platea dictumst. Aliquam aliquam eros eget cursus interdum. Etiam eros mauris, condimentum eget odio ut, convallis tempor turpis.

Curabitur quis luctus quam, in fermentum ipsum. Nullam a consequat lectus. Nulla consectetur, diam luctus placerat accumsan, velit sapien porttitor sem, nec feugiat est elit ac odio. Duis condimentum, arcu id venenatis convallis, metus mi pellentesque magna, nec rutrum nulla sapien sit amet libero. In pretium sodales accumsan. Vivamus pulvinar pretium arcu quis lacinia. Vestibulum sed interdum diam. Aenean id rhoncus ligula, non pretium nisl. Etiam ut nisl volutpat, pharetra nisi sed, facilisis sem. Fusce eget orci nunc. Vivamus iaculis auctor sapien ornare accumsan. Morbi tempus ornare sapien nec consectetur. Maecenas interdum mollis porta. In leo orci, ultrices in ornare ut, dignissim et erat. Quisque eu eros quis justo faucibus porttitor. Phasellus ac rutrum nunc.

Nullam auctor porttitor diam, in aliquam ante. Sed iaculis felis in lorem varius, in molestie velit ultricies. Morbi lectus tellus, condimentum vel sollicitudin et, aliquet eget nibh. In nunc neque, gravida vitae malesuada nec, hendrerit non enim. Integer a volutpat odio. Aliquam non pretium massa, non sagittis augue. Praesent pellentesque vitae ex non efficitur. Donec vel ultricies mauris, nec fermentum metus. Phasellus rutrum libero odio. Duis eu feugiat mi. Vivamus non orci erat. Donec ac ante ac sapien pellentesque commodo convallis a eros. Quisque ultrices, nibh ac maximus congue, purus risus tempus nisl, vitae tempor dui sapien id lacus. Phasellus leo orci, iaculis nec tristique ut, venenatis a nunc. Proin ac accumsan tellus.

Vivamus ullamcorper massa vitae dui placerat, et vehicula odio sollicitudin. Nulla gravida et mauris vel aliquam. Praesent tristique ipsum sem, et pulvinar nulla hendrerit a. In nec felis eget lacus dapibus lobortis. Vestibulum finibus odio et metus eleifend, luctus elementum neque consectetur. Phasellus at eros metus. Sed lacinia tellus at nisl cursus pretium. Duis molestie pulvinar urna, eget bibendum ante accumsan et. Vestibulum eu convallis massa. Fusce ut urna erat.        

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec faucibus ligula. Ut nec consectetur nisi, in euismod ipsum. Curabitur euismod ipsum in enim varius consequat. Ut ligula justo, tristique in lacus non, imperdiet euismod tortor. Integer efficitur euismod erat a malesuada. Aliquam erat volutpat. Morbi ut tempus est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque efficitur est magna, quis pharetra ex hendrerit quis.

Proin tincidunt, quam eu ornare vehicula, nisl ipsum iaculis massa, ut sollicitudin leo nisl at sem. Mauris molestie nunc nec nisl sollicitudin, a venenatis ex dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies, odio at viverra dapibus, ligula ex vulputate libero, sed maximus velit sem et nibh. In hac habitasse platea dictumst. Aliquam aliquam eros eget cursus interdum. Etiam eros mauris, condimentum eget odio ut, convallis tempor turpis.

Curabitur quis luctus quam, in fermentum ipsum. Nullam a consequat lectus. Nulla consectetur, diam luctus placerat accumsan, velit sapien porttitor sem, nec feugiat est elit ac odio. Duis condimentum, arcu id venenatis convallis, metus mi pellentesque magna, nec rutrum nulla sapien sit amet libero. In pretium sodales accumsan. Vivamus pulvinar pretium arcu quis lacinia. Vestibulum sed interdum diam. Aenean id rhoncus ligula, non pretium nisl. Etiam ut nisl volutpat, pharetra nisi sed, facilisis sem. Fusce eget orci nunc. Vivamus iaculis auctor sapien ornare accumsan. Morbi tempus ornare sapien nec consectetur. Maecenas interdum mollis porta. In leo orci, ultrices in ornare ut, dignissim et erat. Quisque eu eros quis justo faucibus porttitor. Phasellus ac rutrum nunc.

Nullam auctor porttitor diam, in aliquam ante. Sed iaculis felis in lorem varius, in molestie velit ultricies. Morbi lectus tellus, condimentum vel sollicitudin et, aliquet eget nibh. In nunc neque, gravida vitae malesuada nec, hendrerit non enim. Integer a volutpat odio. Aliquam non pretium massa, non sagittis augue. Praesent pellentesque vitae ex non efficitur. Donec vel ultricies mauris, nec fermentum metus. Phasellus rutrum libero odio. Duis eu feugiat mi. Vivamus non orci erat. Donec ac ante ac sapien pellentesque commodo convallis a eros. Quisque ultrices, nibh ac maximus congue, purus risus tempus nisl, vitae tempor dui sapien id lacus. Phasellus leo orci, iaculis nec tristique ut, venenatis a nunc. Proin ac accumsan tellus.

Vivamus ullamcorper massa vitae dui placerat, et vehicula odio sollicitudin. Nulla gravida et mauris vel aliquam. Praesent tristique ipsum sem, et pulvinar nulla hendrerit a. In nec felis eget lacus dapibus lobortis. Vestibulum finibus odio et metus eleifend, luctus elementum neque consectetur. Phasellus at eros metus. Sed lacinia tellus at nisl cursus pretium. Duis molestie pulvinar urna, eget bibendum ante accumsan et. Vestibulum eu convallis massa. Fusce ut urna erat.        \`;

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nec faucibus ligula. Ut nec consectetur nisi, in euismod ipsum. Curabitur euismod ipsum in enim varius consequat. Ut ligula justo, tristique in lacus non, imperdiet euismod tortor. Integer efficitur euismod erat a malesuada. Aliquam erat volutpat. Morbi ut tempus est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque efficitur est magna, quis pharetra ex hendrerit quis.

Proin tincidunt, quam eu ornare vehicula, nisl ipsum iaculis massa, ut sollicitudin leo nisl at sem. Mauris molestie nunc nec nisl sollicitudin, a venenatis ex dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies, odio at viverra dapibus, ligula ex vulputate libero, sed maximus velit sem et nibh. In hac habitasse platea dictumst. Aliquam aliquam eros eget cursus interdum. Etiam eros mauris, condimentum eget odio ut, convallis tempor turpis.

Curabitur quis luctus quam, in fermentum ipsum. Nullam a consequat lectus. Nulla consectetur, diam luctus placerat accumsan, velit sapien porttitor sem, nec feugiat est elit ac odio. Duis condimentum, arcu id venenatis convallis, metus mi pellentesque magna, nec rutrum nulla sapien sit amet libero. In pretium sodales accumsan. Vivamus pulvinar pretium arcu quis lacinia. Vestibulum sed interdum diam. Aenean id rhoncus ligula, non pretium nisl. Etiam ut nisl volutpat, pharetra nisi sed, facilisis sem. Fusce eget orci nunc. Vivamus iaculis auctor sapien ornare accumsan. Morbi tempus ornare sapien nec consectetur. Maecenas interdum mollis porta. In leo orci, ultrices in ornare ut, dignissim et erat. Quisque eu eros quis justo faucibus porttitor. Phasellus ac rutrum nunc.

Nullam auctor porttitor diam, in aliquam ante. Sed iaculis felis in lorem varius, in molestie velit ultricies. Morbi lectus tellus, condimentum vel sollicitudin et, aliquet eget nibh. In nunc neque, gravida vitae malesuada nec, hendrerit non enim. Integer a volutpat odio. Aliquam non pretium massa, non sagittis augue. Praesent pellentesque vitae ex non efficitur. Donec vel ultricies mauris, nec fermentum metus. Phasellus rutrum libero odio. Duis eu feugiat mi. Vivamus non orci erat. Donec ac ante ac sapien pellentesque commodo convallis a eros. Quisque ultrices, nibh ac maximus congue, purus risus tempus nisl, vitae tempor dui sapien id lacus. Phasellus leo orci, iaculis nec tristique ut, venenatis a nunc. Proin ac accumsan tellus.

Vivamus ullamcorper massa vitae dui placerat, et vehicula odio sollicitudin. Nulla gravida et mauris vel aliquam. Praesent tristique ipsum sem, et pulvinar nulla hendrerit a. In nec felis eget lacus dapibus lobortis. Vestibulum finibus odio et metus eleifend, luctus elementum neque consectetur. Phasellus at eros metus. Sed lacinia tellus at nisl cursus pretium. Duis molestie pulvinar urna, eget bibendum ante accumsan et. Vestibulum eu convallis massa. Fusce ut urna erat.        \`;

`;

    }
}

